chore: leverage all oras container stuffs in a new task

diff --git a/common/tasks/create-oci-artifact/0.1/create-oci-artifact.yaml b/common/tasks/create-oci-artifact/0.1/create-oci-artifact.yaml
--- a/common/tasks/create-oci-artifact/0.1/create-oci-artifact.yaml
+++ b/common/tasks/create-oci-artifact/0.1/create-oci-artifact.yaml
@@ -48,8 +48,19 @@ spec:
         jq -n --arg exp "$(params.oci-container-expiration)" --arg title "Artifact store for pipelinerun: $(params.test-name)" \
           '{"$manifest": {"quay.expires-after": $exp, "org.opencontainers.image.title": $title}}' > "${TEMP_ANNOTATION_FILE}"
 
-        # Push the container to oci registry
-        oras push "${OCI_STORAGE_CONTAINER}" --username="${OCI_STORAGE_USERNAME}" --password="${OCI_STORAGE_TOKEN}" \
-          --config /dev/null:application/vnd.oras.config.v1+json --annotation-file "${TEMP_ANNOTATION_FILE}"
-
-        exit 1
+        # Push the container to oci registry. Try 5 times in case
+        for i in {1..5}; do
+            if oras push "${OCI_STORAGE_CONTAINER}" --username="${OCI_STORAGE_USERNAME}" --password="${OCI_STORAGE_TOKEN}" \
+                --config /dev/null:application/vnd.oras.config.v1+json --annotation-file "${TEMP_ANNOTATION_FILE}"; then
+                echo "[INFO] oras push succeeded on attempt $i."
+                break
+            else
+                echo "[WARNING] oras push failed on attempt $i. Retrying..."
+                sleep 5
+            fi
+            # Exit with error if all attempts fail
+            if [ $i -eq 5 ]; then
+                echo "[ERROR] oras push failed after 5 attempts."
+                exit 1
+            fi
+        done
diff --git a/common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml b/common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml
--- a/common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml
+++ b/common/tasks/rosa/hosted-cp/rosa-hcp-deprovision/rosa-hcp-deprovision.yaml
@@ -91,9 +91,19 @@ spec:
         QUAY_PASSWORD=$(cat /usr/local/oras-credentials/quay-password)
         oras login -u $QUAY_USERNAME -p $QUAY_PASSWORD quay.io
 
-        echo '{"doc": "README.md"}' > config.json
+        TEMP_ANNOTATION_FILE="$(mktemp)"
+
+        # Fetch the manifest annotations for the container
+        MANIFESTS=$(oras manifest fetch "$(params.oras-container)" | jq .annotations) || {
+            echo "[Error] Failed to fetch manifest from ${OCI_STORAGE_CONTAINER}" >&2
+            exit 1
+        }
+
+        # Create and save the JSON object
+        jq -n --argjson manifest "$MANIFESTS" '{ "$manifest": $manifest }' > "${TEMP_ANNOTATION_FILE}"
+
         oras pull "$(params.oras-container)"
-        oras push "$(params.oras-container)" --config config.json:application/vnd.acme.rocket.config.v1+json \
+        oras push "$(params.oras-container)" --annotation-file "${TEMP_ANNOTATION_FILE}" \
           ./:application/vnd.acme.rocket.docs.layer.v1+tar
     - name: deprovision-rosa
       image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
