Add sprayproxy

diff --git a/common/tasks/gather-artifacts/upload-oras.yaml b/common/tasks/gather-artifacts/upload-oras.yaml
--- a/common/tasks/gather-artifacts/upload-oras.yaml
+++ b/common/tasks/gather-artifacts/upload-oras.yaml
@@ -25,9 +25,19 @@ spec:
     - name: git-org
       type: string
       description: ""
+    - name: cluster-name
+      type: string
+      description: ocp cluster name that you want to delete
+    - name: region
+      type: string
+      description: ocp cluster region where you want to delete
+    - name: hcp-secrets
+      type: string
+      description: The secrets that are used to create the HCP cluster
   steps:
     - name: collect-artifacts
       workingDir: /workspace/cluster-artifacts
+      onError: continue
       image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
       script: |
         #!/bin/sh
@@ -36,6 +46,7 @@ spec:
         curl -sSL https://raw.githubusercontent.com/konflux-qe-incubator/konflux-qe-definitions/onboard_rhtap_e2e/scripts/gather-extra.sh | bash
     - name: inspect-upload-artifacts
       workingDir: /workspace
+      onError: continue
       image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
       env:
         - name: QUAY_USERNAME
@@ -65,6 +76,7 @@ spec:
           ./:application/vnd.acme.rocket.docs.layer.v1+tar
     - name: pull-request-comment
       workingDir: /workspace
+      onError: continue
       image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
       env:
         - name: GITHUB_TOKEN
@@ -90,7 +102,7 @@ spec:
 
         COMMENT=$(cat <<EOF
         {
-          "body": "@$PR_AUTHOR: The following test finished, in case test failed say /retest to rerun all failed tests:\n\nPipelineRun name | Command\n--- | --- | ---\n$TEST_NAME | /retest\n\nTo inspect your test artifacts make sure you have installed ORAS in your local machine. To inspect all test artifacts execute:\n\n\`\`\`shell\nmkdir -p oras-artifacts\ncd oras-artifacts\noras pull $ORAS_CONTAINER\n\`\`\`\n\nFor instructions on how to install ORAS, please refer to the [ORAS installation guide](https://oras.land/docs/installation)."
+          "body": "@$PR_AUTHOR: The following test finished, in case test failed say /retest to rerun all failed tests:\n\nPipelineRun name | Command\n--- | ---\n$TEST_NAME | /retest\n\nTo inspect your test artifacts make sure you have installed ORAS in your local machine. To inspect all test artifacts execute:\n\n\`\`\`shell\nmkdir -p oras-artifacts\ncd oras-artifacts\noras pull $ORAS_CONTAINER\n\`\`\`\n\nFor instructions on how to install ORAS, please refer to the [ORAS installation guide](https://oras.land/docs/installation)."
         }
         EOF
         )
@@ -102,7 +114,55 @@ spec:
             "https://api.github.com/repos/$GIT_ORG/$GIT_REPO/issues/$PR_NUMBER/comments")
 
         if echo "$RESPONSE" | grep -q '"id"'; then
-            echo "Comment posted successfully."
+            echo "[INFO] Comment posted successfully."
         else
-            echo "Failed to post comment. Response: $RESPONSE"
+            echo "[ERROR] Failed to post comment. Response: $RESPONSE"
         fi
+    - name: deprovision-rosa
+      image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
+      env:
+        - name: CLUSTER_NAME
+          value: "$(params.cluster-name)"
+        - name: ROSA_TOKEN
+          valueFrom:
+            secretKeyRef:
+              name: "$(params.hcp-secrets)"
+              key: "ROSA_TOKEN"
+        - name: AWS_ACCESS_KEY_ID
+          valueFrom:
+            secretKeyRef:
+              name: "$(params.hcp-secrets)"
+              key: "AWS_ACCESS_KEY_ID"
+        - name: AWS_SECRET_ACCESS_KEY
+          valueFrom:
+            secretKeyRef:
+              name: "$(params.hcp-secrets)"
+              key: "AWS_SECRET_ACCESS_KEY"
+        - name: REGION
+          value: "$(params.region)"
+      script: |
+        set -o errexit
+        set -o nounset
+        set -o pipefail
+
+        config_aws_creds() {
+            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
+            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
+            aws configure set region "$REGION"
+        }
+
+        if [[ -n "$CLUSTER_NAME"  ]]; then
+            echo "INFO: [$(date +"%Y/%m/%d %H:%M:%S")] Started to destroy cluster [$CLUSTER_NAME]..."
+
+            printf "INFO: Log in to your Red Hat account...\n"
+            config_aws_creds
+            rosa login --token="$ROSA_TOKEN"
+
+            # Here we just trigger the deletion of the cluster, we won't wait for it to be completely deleted
+            rosa delete cluster --region "$REGION" --cluster="$CLUSTER_NAME" -y
+
+        else
+            echo "INFO: No OCP cluster need to be destroyed."
+        fi
+
+        echo "INFO: [$(date +"%Y/%m/%d %H:%M:%S")] Done"
